### ISSUE TITLE
Dynamic subtitles

### ISSUE THREAD

**Issue by nagfriend** [sunil676/NavigationViewAndroid#1]
how can I handle dynamic subtitles; download the subtitles related only to the clicked mainTitle

**Comment by sunil676** [comment]
Hi. Either you can pass the map of title list and child of a subtitle list.

**Comment by fWd82** [comment]
Hello @sunil676 Thank You 
Can you please give us some clue or show us some code for: 
- **HOME**
- **NATURE**
-- Hot
-- Cold
- **TYPE**
-- Type1
-- Type2
- **CONTACT**
Please show us how to do it. Thank You.

**Comment by sunil676** [comment]
It will automatically inflate those list as it is because list inside the list having any child it will inflate otherwise it will ignore base on sublist of a list. You should not worry about for this.
